#!/bin/bash

# Build math-classes
scons -C ./math-classes/src -j8

# Build the Makefile
touch .depend
coq_makefile integers.v *.v -R . SAMPL -R ./math-classes/src MathClasses -arg "-R . SAMPL -R ./math-classes/src MathClasses" > Makefile

# Hack to generate the .v.d files in a .dep directory
mkdir .dep
sed -i 's/-include $(addsuffix .d,$(VFILES))/-include $(addprefix .dep\/,$(addsuffix .d,$(VFILES)))/' Makefile
sed -i 's/%.v.d: %.v/.dep\/%.v.d: %.v/' Makefile
sed -i 's/rm -f $(VOFILES) $(VIFILES) $(GFILES) $(VFILES:.v=.v.d) $(VFILES:=.beautified) $(VFILES:=.old)/rm -f $(VOFILES) $(VIFILES) $(GFILES) $(addprefix .dep\/, $(VFILES:.v=.v.d)) $(VFILES:=.beautified) $(VFILES:=.old)/' Makefile

# Make everything ..
make clean
make depend
make
